# -*- coding: utf-8 -*-
"""Contoh Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196tCS2VenTiFn6RtIIStNMIMjFmLvg7v
"""

#Contoh Algorithms

import numpy as np

#membuat array
df = np.array([1,2,3])
df

df = np.array([1,2,3])
df.dtype

#multidemensional array
arrku = np.array([[1,2,3,4,5], [2,4,6,8.10]])
arrku

#operasi aritmatika
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print("Penjumlahan =", arr_A + arr_B)
print("Pengurangan =", arr_A - arr_B)
print("Penrkalian =", arr_A * arr_B)
print("Pembagian =", arr_A / arr_B)
print("Perpangktan =", arr_A ** arr_B)