# -*- coding: utf-8 -*-
"""Contoh Struktur Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbNO1RGjSWulZz6zo1EaCP3cxqPcmfKT
"""

#Contoh struktur data (list)

#List
tinggi_badan = [162, 177, 182, 150, 166]
print(tinggi_badan[0])

print(tinggi_badan[1:5])

print(tinggi_badan[:4])

#menambah element pada list
murid = ['ayu', 'bagus', 'fajar', 'cahyo', 'ani']

murid.append('riski')
print(murid)

#menghapus element list
murid = ['ayu', 'bagus', 'fajar', 'cahyo', 'ani']
del murid[2]
print(murid)